IRONTASK/irontaskweb/irontaskweb/urlpatterns/urls.py
from irontaskweb import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include

app_name = "irontask"
urlpatterns = [
    url(r"^$", views.home),
    url(r"^home/$", views.home, name="home"),

    url(r'^task/', include('irontaskweb.urlpatterns.task_urls')),
    url(r'^board/', include('irontaskweb.urlpatterns.board_urls')),
    url(r'^plan/', include('irontaskweb.urlpatterns.plan_urls')),

    url(r'^api/', include('irontaskweb.urlpatterns.api_urls')),
    url(r"^registration/$", views.registration, name="registration"),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout')
]

IRONTASK/irontaskweb/irontaskweb/urls.py
from django.conf.urls import url, include
# from django.contrib import admin
#
# from . import views

urlpatterns = [
    url(r'', include('irontaskweb.urlpatterns.urls')),
    # url(r'^irontask/', include('irontaskweb.urlpatterns.urls'))
]

IRONTASK/irontaskweb/irontaskweb/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect
from django.urls import reverse

from irontaskweb import get_service
from irontasklib.model import models as model
from irontasklib.model import enums as enum
from irontasklib.model.enums import Periodicity
from irontasklib.services import exceptions as ex
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from collections import namedtuple
from irontaskweb.forms import (TaskForm, BoardForm, PlanForm)


def registration(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password2']

            user = authenticate(username=username, password=password)
            auth_login(request, user)
            get_service().add_user(model.User(login=user.username, user_id=user.id))
            return HttpResponseRedirect(reverse('irontask:home'))
    else:
        form = UserCreationForm()

    context = {'form': form}
    return render(request=request, template_name='profile/registration.html', context=context)


def login(request):
    context = {}
    if request.method == 'POST':
        try:
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return HttpResponseRedirect(reverse('irontask:home'))
            else:
                context['message'] = 'Invalid login'
        except Exception:
            context['message'] = 'Unknown error'
    return render(request=request, template_name='profile/login.html', context=context)


def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse('irontask:login'))


@login_required(login_url='/login/')
def home(request):
    user_id = request.user.id
    tasks = get_service().get_user_tasks(current_user_id=user_id,
                                         statuses=[enum.TaskStatus.ACTIVE.value, enum.TaskStatus.OVERDUE.value,
                                                   enum.TaskStatus.REQUEST.value, enum.TaskStatus.COMPLETED.value,
                                                   enum.TaskStatus.FAILED.value])
    boards = get_service().get_user_boards(current_user_id=user_id, status=enum.BoardStatus.OPENED.value)
    plans = [get_service().get_plan_view(plan.plan_id, current_user_id=user_id)
             for plan in get_service().get_user_plans(current_user_id=user_id)]
    messages = [get_service().get_message_view(message.message_id, current_user_id=user_id) for message in get_service().get_user_messages(current_user_id=user_id)]
    messages = sorted(messages, key=lambda message: message.message.date, reverse=True)
    context = {'tasks': tasks, 'boards': boards, 'plans': plans, 'messages': messages}
    return render(request, 'home.html', context=context)


@login_required(login_url='/login/')
def show_task(request, task_id):
    user_id = request.user.id

    try:
        task_view = get_service().get_task_view(task_id, current_user_id=user_id)
    except ex.NotFoundError as e:
        return page404(str(e))
    except ex.AuthorizationError as e:
        return page403(str(e))

    messages = [get_service().get_message_view(message.message_id, current_user_id=user_id)
                for message in task_view.messages]
    task_view.messages = sorted(messages, key=lambda message: message.message.date, reverse=True)

    task_view.subtasks = []
    TaskTuple = namedtuple('TaskTuple', ['task', 'relation'])
    for relation in task_view.child_relations:
        related_task = get_service().get_task(relation.child_id, current_user_id=user_id)
        task_view.subtasks.append(TaskTuple(related_task, relation))

    return render(request, 'task/details.html', context=vars(task_view))


@login_required(login_url='/login/')
def show_tasks(request):
    user_id = request.user.id

    tasks = get_service().get_user_tasks(current_user_id=user_id,
                                         statuses=[enum.TaskStatus.ACTIVE.value, enum.TaskStatus.OVERDUE.value,
                                                   enum.TaskStatus.REQUEST.value, enum.TaskStatus.COMPLETED.value,
                                                   enum.TaskStatus.FAILED.value])
    return render(request, 'task/tasks.html', context={'tasks': tasks})


@login_required(login_url='/login/')
def filter_tasks(request):
    user_id = request.user.id

    term = request.POST['search_term']
    tags = term.split(',')

    filtered_tasks = get_service().get_tasks_by_tags(tags=tags, current_user_id=user_id)
    return render(request, 'task/tasks.html', context={'tasks': filtered_tasks})


@login_required(login_url='/login/')
def add_task(request):
    user_id = request.user.id
    if request.method == 'GET':
        form = TaskForm()
    else:
        form = TaskForm(request.POST)
        if form.is_valid():
            arg_dict = form.cleaned_data

            task = model.Task(title=arg_dict[model.TASK_TITLE], description=arg_dict[model.TASK_DESCRIPTION],
                              priority=arg_dict[model.TASK_PRIORITY], status=arg_dict[model.TASK_STATUS],
                              board_id=arg_dict[model.TASK_BOARD_ID])
            task = get_service().add_task(task, current_user_id=user_id)

            for date_type, date_type_key in [(enum.TaskDateType.START.value, model.TASK_DATE_START),
                                             (enum.TaskDateType.END.value, model.TASK_DATE_END),
                                             (enum.TaskDateType.EVENT.value, model.TASK_DATE_EVENT)]:
                if form.cleaned_data[date_type_key]:
                    get_service().add_task_date(model.TaskDate(form.cleaned_data[date_type_key].replace(tzinfo=None),
                                                               date_type, task.task_id),
                                                current_user_id=user_id)

            new_tags = [model.Tag(task.task_id, tag) for tag in form.cleaned_data[model.TAGS].split(',')]
            get_service().add_tags(new_tags, current_user_id=user_id)

            return HttpResponseRedirect(reverse('irontask:show_task', args=[task.task_id]))
    context = {'form': form, 'is_creation': True}
    return render(request=request, template_name="task/edit.html", context=context)


@login_required(login_url='/login/')
def update_task(request, task_id):
    user_id = request.user.id
    try:
        task = get_service().get_task(task_id, current_user_id=user_id)
        dates = get_service().get_task_dates_filtered(date_types=[enum.TaskDateType.START.value,
                                                                  enum.TaskDateType.END.value,
                                                                  enum.TaskDateType.EVENT.value],
                                                      task_id=task.task_id, current_user_id=user_id)
        board = get_service().get_board(task.board_id, current_user_id=user_id) if task.board_id else None
        start_date = next(iter([date for date in dates if date.date_type == enum.TaskDateType.START.value] or []), None)
        end_date = next(iter([date for date in dates if date.date_type == enum.TaskDateType.END.value] or []), None)
        event_date = next(iter([date for date in dates if date.date_type == enum.TaskDateType.EVENT.value] or []), None)
        tags = get_service().get_task_tags(task_id=task_id, current_user_id=user_id)

    except ex.NotFoundError as e:
        return page404(str(e))
    except ex.AuthorizationError as e:
        return page404(str(e))

    if request.method == 'GET':
        initial = {
            model.TASK_TITLE: task.title,
            model.TASK_STATUS: task.status,
            model.TASK_PRIORITY: task.priority,
            model.TASK_DESCRIPTION: task.description,
            'date_type': 2 if event_date else 1 if start_date or end_date else 0,
            model.TASK_DATE_START: format(start_date.date, '%Y-%m-%dT%H:%M') if start_date else None,
            model.TASK_DATE_END: format(end_date.date, '%Y-%m-%dT%H:%M') if end_date else None,
            model.TASK_DATE_EVENT: format(event_date.date, '%Y-%m-%dT%H:%M') if event_date else None,
            model.TAGS: ','.join([tag.text for tag in tags]),
            model.TASK_BOARD_ID: task.board_id,
            'board_title': board.title if board else None
        }
        form = TaskForm(initial=initial)
    else:
        form = TaskForm(request.POST)
        if form.is_valid():
            arg_dict = form.cleaned_data

            for key, value in arg_dict.items():
                if key in dir(model.Task):
                    setattr(task, key, value)

            get_service().update_task(task, current_user_id=user_id)

            for date in dates:
                if date:
                    get_service().remove_task_date(date.task_date_id, current_user_id=user_id)

            for date_type, date_type_key in [(enum.TaskDateType.START.value, model.TASK_DATE_START),
                                             (enum.TaskDateType.END.value, model.TASK_DATE_END),
                                             (enum.TaskDateType.EVENT.value, model.TASK_DATE_EVENT)]:
                if form.cleaned_data[date_type_key]:
                    get_service().add_task_date(model.TaskDate(form.cleaned_data[date_type_key].replace(tzinfo=None),
                                                               date_type, task_id),
                                                current_user_id=user_id)

            for tag in tags:

IRONTASK/irontaskweb/irontaskweb/templates/profile/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>IRONTASK is the best tasktracker ever</title>
	<meta charset="utf-8">
	<meta name="author" content="Artem Glotov">
	<meta name="description" content="IRONTASK is the best tasktracker ever"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    <div>
        <div class="container">
            <div class="row main">
                <div class="main-login main-center">
                    <div class="panel-heading">
                       <div class="panel-title text-center">
                            <h1 class="title">IRONTASK</h1>
                            <hr />
                        </div>
                    </div>
                    <form class="form-horizontal" method="post" action="{% url 'irontask:login' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username" class="cols-sm-2 control-label">Username</label>
                            <input type="text" class="form-control" name="username" id="username"  placeholder="Enter your Username"/>
                        </div>

                        <div class="form-group">
                            <label for="password" class="cols-sm-2 control-label">Password</label>
                            <input type="password" class="form-control" name="password" id="password"  placeholder="Enter your Password"/>
                        </div>

                        <div class="form-group ">
                            <button type="submit" class="btn btn-primary btn-lg btn-block login-button">Login</button>
                        </div>

                        <div class="login-register">
                            <a href="{% url 'irontask:registration' %}">Register</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>

IRONTASK/irontaskweb/irontaskweb/templates/profile/registration.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>IRONTASK is the best tasktracker ever</title>
	<meta charset="utf-8">
	<meta name="author" content="Artem Glotov">
	<meta name="description" content="IRONTASK is the best tasktracker ever"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    <div>
        <div class="container">
            <div class="row main">
                <div class="main-login main-center">
                    <div class="panel-heading">
                       <div class="panel-title text-center">
                            <h1 class="title">IRONTASK</h1>
                            <hr />
                        </div>
                    </div>
                    {% if form.errors %}
                    <p>{{form.error_messages}}</p>
                    {% endif %}
                    <form class="form-horizontal" method="post" action="{% url 'irontask:registration' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username" class="cols-sm-2 control-label">Username</label>
                            <input type="text" class="form-control" name="username" id="username"  placeholder="Enter your Username"/>
                        </div>

                        <!--<div class="form-group">-->
                            <!--<label for="email" class="cols-sm-2 control-label">Your Email</label>-->
                            <!--<input type="text" class="form-control" name="email" id="email"  placeholder="Enter your Email"/>-->
                        <!--</div>-->

                        <div class="form-group">
                            <label for="password1" class="cols-sm-2 control-label">Password</label>
                            <input type="password" class="form-control" name="password1" id="password1"  placeholder="Enter your Password"/>
                        </div>

                        <div class="form-group">
                            <label for="password2" class="cols-sm-2 control-label">Confirm Password</label>
                            <input type="password" class="form-control" name="password2" id="password2"  placeholder="Confirm your Password"/>
                        </div>

                        <div class="form-group ">
                            <button type="submit" class="btn btn-primary btn-lg btn-block login-button">Register</button>
                        </div>
                        <div class="login-register">
                            <a href="{% url 'irontask:login' %}">Login</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>