IRONTASK/irontaskweb/irontaskweb/urlpatterns/urls.py
from irontaskweb import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include

app_name = "irontask"
urlpatterns = [
    url(r"^$", views.home),
    url(r"^home/$", views.home, name="home"),

    url(r'^task/', include('irontaskweb.urlpatterns.task_urls')),
    url(r'^board/', include('irontaskweb.urlpatterns.board_urls')),
    url(r'^plan/', include('irontaskweb.urlpatterns.plan_urls')),

    url(r'^api/', include('irontaskweb.urlpatterns.api_urls')),
    url(r"^registration/$", views.registration, name="registration"),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout')
]

IRONTASK/irontaskweb/irontaskweb/urls.py
from django.conf.urls import url, include
# from django.contrib import admin
#
# from . import views

urlpatterns = [
    url(r'', include('irontaskweb.urlpatterns.urls')),
    # url(r'^irontask/', include('irontaskweb.urlpatterns.urls'))
]

IRONTASK/irontaskweb/irontaskweb/forms.py
from django import forms
import re
from irontasklib.model import enums as enum
from irontasklib.model import models as model
from irontasklib.model.enums import Periodicity
from django.forms import ValidationError
from irontaskweb.utilities import get_enum_choices

periodicity_regex = '((?P<years>\d+)Y )?((?P<months>\d+)M )?((?P<days>\d+)D )?((?P<hours>\d+)h )?((?P<minutes>\d+)m )?'


class TaskForm(forms.Form):
    title = forms.CharField(max_length=50, required=True)
    status = forms.ChoiceField(choices=get_enum_choices(enum.TaskStatus),
                               required=False)
    priority = forms.ChoiceField(choices=get_enum_choices(enum.TaskPriority),
                                 initial=enum.TaskPriority.NORMAL.value)
    description = forms.CharField(widget=forms.Textarea, required=False, max_length=500)

    start_date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=False,
                                     input_formats=['%Y-%m-%dT%H:%M'], localize=False)
    end_date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=False,
                                   input_formats=['%Y-%m-%dT%H:%M'], localize=False)
    event_date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=False,
                                     input_formats=['%Y-%m-%dT%H:%M'], localize=False)

    date_type = forms.ChoiceField(choices=[(0, "Without dates"), (1, "Start-end dates"), (2, "Event date")],
                                  initial=0, widget=forms.RadioSelect())
    tags = forms.CharField(widget=forms.TextInput(attrs={'data-role': 'tagsinput'}), required=False)

    board_title = forms.CharField(required=False)

    board_id = forms.IntegerField(initial=None, required=False)

    def clean_start_date(self):
        form_data = self.data
        start_date = form_data.get(model.TASK_DATE_START, None)
        end_date = form_data.get(model.TASK_DATE_END, None)

        if not start_date and end_date:
            raise ValidationError("If you specify end date you must specify start date")

        if start_date is not None and end_date is not None:
            if end_date < start_date:
                raise ValidationError("Start date can't be later than end date")

        return self.cleaned_data.get(model.TASK_DATE_START, None)

    def clean_end_date(self):
        form_data = self.data
        start_date = form_data.get(model.TASK_DATE_START, None)
        end_date = form_data.get(model.TASK_DATE_END, None)

        if start_date and not end_date:
            raise ValidationError("If you specify end date you must specify start date")

        if start_date is not None and end_date is not None:
            if end_date < start_date:
                raise ValidationError("Start date can't be later than end date")

        return self.cleaned_data.get(model.TASK_DATE_END, None)


class BoardForm(forms.Form):
    title = forms.CharField(max_length=50, required=True)

    description = forms.CharField(widget=forms.Textarea, required=False, max_length=500)
    status = forms.ChoiceField(choices=get_enum_choices(enum.BoardStatus),
                               required=False, initial=enum.BoardStatus.OPENED.value)
    board_type = forms.ChoiceField(choices=get_enum_choices(enum.BoardType),
                                   required=False, initial=enum.BoardType.SINGLE.value)


class PlanForm(forms.Form):
    title = forms.CharField(max_length=50, required=False)

    priority = forms.ChoiceField(choices=get_enum_choices(enum.TaskPriority),
                                 initial=enum.TaskPriority.NORMAL.value)
    description = forms.CharField(widget=forms.Textarea, initial=None, required=False, max_length=500)

    tags = forms.CharField(widget=forms.TextInput(attrs={'data-role': 'tagsinput'}), required=False)

    periodicity = forms.CharField(widget=forms.TextInput(
        attrs={'title': '1Y - 1 year\n4M - 4 month\n3D - 3 days\n12h - 12 hours\n7m - 7 minutes',
               'placeholder': 'Write period like \'#Y #M #m\' or \'#M #D #h #m\''}),
        initial=None, required=False
    )

    end_type = forms.ChoiceField(choices=get_enum_choices(enum.PlanEndType), required=True,
                                 initial=enum.PlanEndType.NEVER.value, widget=forms.RadioSelect())
    status = forms.ChoiceField(choices=get_enum_choices(enum.PlanStatus),
                               required=False, initial=enum.PlanStatus.ON.value)
    start_date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=True,
                                     input_formats=['%Y-%m-%dT%H:%M'], localize=False)
    end_date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=False,
                                   input_formats=['%Y-%m-%dT%H:%M'], localize=False)
    count_iteration = forms.IntegerField(required=False, min_value=1)

    task_type = forms.ChoiceField(choices=[(0, "Existing task"), (1, "New task")], required=False,
                                  widget=forms.RadioSelect(), initial=0)

    board_title = forms.CharField(required=False)

    board_id = forms.IntegerField(initial=None, required=False)

    task_title = forms.CharField(required=False)

    task_id = forms.IntegerField(initial=None, required=False)

    def clean_periodicity(self):
        periodicity = self.cleaned_data[model.PLAN_PERIODICITY]
        periodicity = periodicity.strip() + ' '
        pattern = re.compile(periodicity_regex)
        match = pattern.match(periodicity)
        if match:
            result = match.groupdict()
            return result
        else:
            raise ValidationError('Period format needs to be "##Y ##M ##D ##h ##m"')

    def clean_end_type(self):
        end_type = self.cleaned_data.get(model.PLAN_END_TYPE)
        return int(end_type)

    # def clean_interval(self):
    #     interval = self.cleaned_data.get(model.PLAN_INTERVAL)
    #     return int(interval)

    def clean_count_iteration(self):
        count_iteration = self.cleaned_data.get(model.PLAN_COUNT_ITERATION)
        if count_iteration:
            return int(count_iteration)
        return count_iteration

    def clean_task_id(self):
        form_data = self.cleaned_data
        task_id = form_data.get(model.TASK_ID, None)
        title = form_data.get(model.TASK_TITLE, None)
        if not task_id and not title:
            raise ValidationError("You must specify existing task or add new.")
        return task_id

    def clean_task_title(self):
        form_data = self.cleaned_data
        task_id = form_data.get(model.TASK_ID, None)
        title = form_data.get(model.TASK_TITLE, None)
        if not task_id and not title:
            raise ValidationError("You must specify existing task or add new.")
        return

    def clean_start_date(self):
        form_data = self.cleaned_data
        start_date = form_data.get(model.PLAN_START, None)
        end_date = form_data.get(model.PLAN_END, None)
        if start_date is not None and end_date is not None:
            if end_date < start_date:
                raise ValidationError("Start date can't be later than end date")
        return start_date

    def clean_end_date(self):
        form_data = self.cleaned_data
        start_date = form_data.get(model.PLAN_START, None)
        end_date = form_data.get(model.PLAN_END, None)
        if start_date is not None and end_date is not None:
            if end_date < start_date:
                raise ValidationError("Start date can't be later than end date")
        return end_date

IRONTASK/irontaskweb/irontaskweb/templates/plan/details.html
{% extends "base.html" %}

{% block head_title %}
    <title>Plan's details</title>
{% endblock %}

{% block content %}
<div class="row" style="height:100vh;">
    <div class="col-md-6 h-100">
        <h1><span class="badge badge-{% if plan.status == 1 %}primary{% else %}danger{% endif %}">{{plan.plan_id}} Plan</span>
            <button onclick="location.href='{% url 'irontask:update_plan' plan.plan_id%}'"
               class="btn btn-outline-secondary">
                <span class="glyphicon glyphicon-pencil"></span>
            </button>
            <button onclick="$('#remove_accept').modal('show');"
               class="btn btn-outline-secondary">
                <span class="glyphicon glyphicon-trash"></span>
            </button>
        </h1>
        <h1>{{task.title}}</h1>

        {% if tags %}
            <div class="form-group">
                {% for tag in tags %}
                    <span class="badge badge-info">{{tag.text}}</span>
                {% endfor %}
            </div>
        {% endif %}

        {% if task.description %}
            <p>{{task.description}}</p>
        {% endif %}

        {% if board %}
            <div onclick="location.href='{% url 'irontask:show_board' board.board_id %}'"
                 style="cursor: pointer">
                <p><span class="glyphicon glyphicon-list-alt"></span> {{board.title}}</p>
            </div>
        {% endif %}

        <div>
            <p>
                <span class="glyphicon glyphicon-repeat"></span>
                <span>Repeat every {{plan.periodicity}}</span>
            </p>
        </div>

        <div>
            <p><span class="glyphicon glyphicon-play"></span> Created: {{plan.date_create.date}}</p>
        </div>

        {% if plan.end_type == 2 and plan.start_date and plan.end_date %}
            <div>
                <p><span class="glyphicon glyphicon-time"></span> {{plan.start_date.date}} - {{plan.end_date.date}}</p>
            </div>
        {% else %}
            <div>
                <p><span class="glyphicon glyphicon-time"></span> Start: {{plan.start_date.date}}</p>
            </div>
        {% endif %}

        {% if plan.end_type == 3 and plan.count_iteration %}
            <div>
                <p><span class="glyphicon glyphicon-refresh"></span> {{plan.current_iteration}}/{{plan.count_iteration}} times</p>
            </div>
        {% endif %}



        {% if date_event %}
           <div>
                <p><span class="glyphicon glyphicon-time"></span> {{date_event.date}}</p>
           </div>
        {% elif date_start and date_end %}
        <div>
            <p><span class="glyphicon glyphicon-time"></span> {{date_start.date}} - {{date_end.date}}</p>
        </div>
        {% endif %}

        <div class="d-flex flex-row">
            {% if creator %}
                <div class="card">
                    <h5 class="card-header">Creator</h5>
                    <div class="card-body">
                        <p class="card-text">{{creator.login}}</p>
                    </div>
                </div>
            {% endif %}

            {% if executors %}
                <div class="card">
                    <h5 class="card-header">Executors</h5>
                    <div class="card-body">
                        {% for executor in executors %}
                            <p class="card-text">{{executor.login}}</p>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}

            {% if observers %}
                <div class="card">
                    <h5 class="card-header">Observers</h5>
                    <div class="card-body">
                        {% for observer in observers %}
                            <p class="card-text">{{observer.login}}</p>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>

<div id="success" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Remove</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>The plan and the template task were successfully removed</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="location.href='{% url 'irontask:home' %}'">OK</button>
            </div>
        </div>
    </div>
</div>

<div id="remove_accept" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Remove</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to remove this plan and connected task?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="removePlan()">Yes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="$('#remove_accept').modal('hide');">Cancel</button>
            </div>
        </div>
    </div>
</div>

<script>
    function removePlan() {
        $.post("{% url 'irontask:remove_plan' %}", { 'plan_id': {{plan.plan_id}}, 'csrfmiddlewaretoken': "{{ csrf_token }}", })
         .done(function (data) {
            if(data.success == 'true') {
                $("#remove_accept").modal('hide');
                $("#success").modal('show');
            }
         });
    }
</script>
{% endblock %}

IRONTASK/irontaskweb/irontaskweb/templates/plan/edit.html
{% extends "base.html" %}

{% block head_title %}
    <title>Plan's {% if is_creation %}creation{% else %}update{% endif %}</title>
{% endblock %}

{% block content %}
{% load filters %}
<div style="height:100vh;">
    <form id="task_form" action="{% if is_creation %}{% url 'irontask:add_plan' %}{% else %}{% url 'irontask:update_plan' plan_id %}{% endif %}" method="post">
        {% csrf_token %}
        <div class="form-group row" style="align-items:center;">
            <div class="col-sm-2">
                <h1>
                    <span class="badge badge-secondary">
                        {% if plan_id %}
                            {{plan_id}}
                        {% else %}
                            <span class="glyphicon glyphicon-hourglass"></span>
                        {% endif %}
                        Plan
                    </span>
                </h1>
            </div>
            {% if is_creation %}
                <div class="col-sm-10">
                    {% for checkbox in form.task_type %}
                        <div class="form-check form-check-inline" onclick="changeTaskType()">
                            {{checkbox}}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <div id="task-new-block">
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Title</label>
                <div class="col-sm-10">
                    {{form.title|css:'form-control'}}
                    <div>
                    {% for error in form.title.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Tags</label>
                <div class="col-sm-10">
                    {{form.tags}}
                    <div>
                    {% for error in form.tags.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Description</label>
                <div class="col-sm-10">
                    {{form.description|css:'form-control'}}
                    <div>
                    {% for error in form.description.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Priority</label>
                <div class="col-sm-10">
                    {{form.priority|css:'form-control'}}
                    <div>
                    {% for error in form.priority.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Board</label>
                <div class="col-sm-10">
                    {{form.board_title|css:'form-control'}}
                    {{form.board_id.as_hidden}}
                    <div>
                    {% for error in form.board_id.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
                </div>
            </div>
        </div>

        {% if is_creation %}
            <div id="task-existing-block">
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Task</label>
                    <div class="col-sm-10">
                        {{form.task_title|css:'form-control'}}
                        {{form.task_id.as_hidden}}
                        <div>
                            {% for error in form.task_id.errors %}
                                <p style="color: red">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Status</label>
            <div class="col-sm-10">
                {{form.status|css:'form-control'}}
                <div>
                    {% for error in form.status.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Repeat</label>
            <div class="col-sm-10">
                {{form.periodicity|css:'form-control'}}
                <div>
                    {% for error in form.periodicity.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Start date</label>
            <div class="col-sm-10">
                {{form.start_date|css:'form-control'}}
                <div>
                    {% for error in form.start_date.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div>
             <div class="form-group row">
                <label class="col-sm-2 col-form-label">End</label>
                <div class="col-sm-10">
                    {% for checkbox in form.end_type %}
                        <div class="form-check form-check-inline" onclick="changeEndType()">
                            {{checkbox}}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>



        <div id="some-times-block">
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Count repetition</label>
                <div class="col-sm-10">
                    {{form.count_iteration|css:'form-control'}}
                    <div>
                    {% for error in form.count_iteration.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
                </div>
            </div>
        </div>

        <div id="end-date-block">
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">End date</label>
                <div class="col-sm-10">
                    {{form.end_date|css:'form-control'}}
                    <div>
                    {% for error in form.end_date.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
                </div>
            </div>
        </div>


        <button type="button" onclick="submitForm()" class="btn btn-success d-flex mx-auto">{% if is_creation %}Add{% else %}Update{% endif %}</button>
    </form>
</div>
<script>
    $(document).ready(function() {
        changeTaskType();
        changeEndType();

         $('#id_board_title').autocomplete({
            minLength: 1,
            delay: 300,
            source: function(request, response) {
                $.post({
                    url: '{% url 'irontask:get_boards' %}',
                    data: { 'term': request.term, 'csrfmiddlewaretoken': "{{ csrf_token }}" },
                    success: function(data) {
                        response(data);
                    }
                });
            },
            focus: function(event, ui) {
                $('#id_board_title').val( ui.item.label );
                return false;
            },
            select: function(event, ui) {
                $('#id_board_title').val(ui.item.label)
                $('#id_board_id').val(ui.item.value);
                return false;
            }
        });

        {% if is_creation %}
            $('#id_task_title').autocomplete({
                minLength: 1,
                delay: 300,
                source: function(request, response) {
                    $.post({
                        url: '{% url 'irontask:get_tasks' %}',
                        data: { 'term': request.term, 'csrfmiddlewaretoken': "{{ csrf_token }}" },
                        success: function(data) {
                            response(data);
                        }
                    });
                },
                focus: function(event, ui) {
                    $('#id_task_title').val( ui.item.label );
                    return false;
                },
                select: function(event, ui) {
                    $('#id_task_title').val(ui.item.label)
                    $('#id_task_id').val(ui.item.value);
                    return false;
                }
            });
        {% endif %}

    });

    function submitForm() {
        $('#task_form').submit();
    }

    function changeTaskType() {
        if($('#id_task_type_0:checked').length) {
            $('#task-new-block').css('display', 'none')
            $('#task-existing-block').css('display', 'block')
        }
        if($('#id_task_type_1:checked').length) {
            $('#task-new-block').css('display', 'block')
            $('#task-existing-block').css('display', 'none')
        }
    }

    function changeEndType() {
        if($('#id_end_type_0:checked').length) {
            $('#some-times-block').css('display', 'none')
            $('#end-date-block').css('display', 'none')
        }
        if($('#id_end_type_1:checked').length) {
            $('#some-times-block').css('display', 'none')
            $('#end-date-block').css('display', 'block')
        }
        if($('#id_end_type_2:checked').length) {
            $('#some-times-block').css('display', 'block')
            $('#end-date-block').css('display', 'none')
        }
    }
</script>
{% endblock %}

IRONTASK/irontaskweb/irontaskweb/templates/plan/plans.html
{% extends "base.html" %}

{% block head_title %}
	<title>Plans</title>
{% endblock %}

{% block content %}
<div class="h-100">
    <h3>Plans</h3>

    <div class="card-deck">
        {% for plan in plans %}
            {% include "components/plan_component.html" with plan_view=plan %}
        {% empty %}
        <div>You have not any plans</div>
        {% endfor %}
    </div>
</div>
{% endblock %}