IRONTASK/irontaskweb/irontaskweb/urlpatterns/urls.py
from irontaskweb import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include

app_name = "irontask"
urlpatterns = [
    url(r"^$", views.home),
    url(r"^home/$", views.home, name="home"),

    url(r'^task/', include('irontaskweb.urlpatterns.task_urls')),
    url(r'^board/', include('irontaskweb.urlpatterns.board_urls')),
    url(r'^plan/', include('irontaskweb.urlpatterns.plan_urls')),

    url(r'^api/', include('irontaskweb.urlpatterns.api_urls')),
    url(r"^registration/$", views.registration, name="registration"),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout')
]

IRONTASK/irontaskweb/irontaskweb/urls.py
from django.conf.urls import url, include
# from django.contrib import admin
#
# from . import views

urlpatterns = [
    url(r'', include('irontaskweb.urlpatterns.urls')),
    # url(r'^irontask/', include('irontaskweb.urlpatterns.urls'))
]

IRONTASK/irontaskweb/irontaskweb/forms.py
from django import forms
import re
from irontasklib.model import enums as enum
from irontasklib.model import models as model
from irontasklib.model.enums import Periodicity
from django.forms import ValidationError
from irontaskweb.utilities import get_enum_choices

periodicity_regex = '((?P<years>\d+)Y )?((?P<months>\d+)M )?((?P<days>\d+)D )?((?P<hours>\d+)h )?((?P<minutes>\d+)m )?'


class TaskForm(forms.Form):
    title = forms.CharField(max_length=50, required=True)
    status = forms.ChoiceField(choices=get_enum_choices(enum.TaskStatus),
                               required=False)
    priority = forms.ChoiceField(choices=get_enum_choices(enum.TaskPriority),
                                 initial=enum.TaskPriority.NORMAL.value)
    description = forms.CharField(widget=forms.Textarea, required=False, max_length=500)

    start_date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=False,
                                     input_formats=['%Y-%m-%dT%H:%M'], localize=False)
    end_date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=False,
                                   input_formats=['%Y-%m-%dT%H:%M'], localize=False)
    event_date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=False,
                                     input_formats=['%Y-%m-%dT%H:%M'], localize=False)

    date_type = forms.ChoiceField(choices=[(0, "Without dates"), (1, "Start-end dates"), (2, "Event date")],
                                  initial=0, widget=forms.RadioSelect())
    tags = forms.CharField(widget=forms.TextInput(attrs={'data-role': 'tagsinput'}), required=False)

    board_title = forms.CharField(required=False)

    board_id = forms.IntegerField(initial=None, required=False)

    def clean_start_date(self):
        form_data = self.data
        start_date = form_data.get(model.TASK_DATE_START, None)
        end_date = form_data.get(model.TASK_DATE_END, None)

        if not start_date and end_date:
            raise ValidationError("If you specify end date you must specify start date")

        if start_date is not None and end_date is not None:
            if end_date < start_date:
                raise ValidationError("Start date can't be later than end date")

        return self.cleaned_data.get(model.TASK_DATE_START, None)

    def clean_end_date(self):
        form_data = self.data
        start_date = form_data.get(model.TASK_DATE_START, None)
        end_date = form_data.get(model.TASK_DATE_END, None)

        if start_date and not end_date:
            raise ValidationError("If you specify end date you must specify start date")

        if start_date is not None and end_date is not None:
            if end_date < start_date:
                raise ValidationError("Start date can't be later than end date")

        return self.cleaned_data.get(model.TASK_DATE_END, None)


class BoardForm(forms.Form):
    title = forms.CharField(max_length=50, required=True)

    description = forms.CharField(widget=forms.Textarea, required=False, max_length=500)
    status = forms.ChoiceField(choices=get_enum_choices(enum.BoardStatus),
                               required=False, initial=enum.BoardStatus.OPENED.value)
    board_type = forms.ChoiceField(choices=get_enum_choices(enum.BoardType),
                                   required=False, initial=enum.BoardType.SINGLE.value)


class PlanForm(forms.Form):
    title = forms.CharField(max_length=50, required=False)

    priority = forms.ChoiceField(choices=get_enum_choices(enum.TaskPriority),
                                 initial=enum.TaskPriority.NORMAL.value)
    description = forms.CharField(widget=forms.Textarea, initial=None, required=False, max_length=500)

    tags = forms.CharField(widget=forms.TextInput(attrs={'data-role': 'tagsinput'}), required=False)

    periodicity = forms.CharField(widget=forms.TextInput(
        attrs={'title': '1Y - 1 year\n4M - 4 month\n3D - 3 days\n12h - 12 hours\n7m - 7 minutes',
               'placeholder': 'Write period like \'#Y #M #m\' or \'#M #D #h #m\''}),
        initial=None, required=False
    )

    end_type = forms.ChoiceField(choices=get_enum_choices(enum.PlanEndType), required=True,
                                 initial=enum.PlanEndType.NEVER.value, widget=forms.RadioSelect())
    status = forms.ChoiceField(choices=get_enum_choices(enum.PlanStatus),
                               required=False, initial=enum.PlanStatus.ON.value)
    start_date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=True,
                                     input_formats=['%Y-%m-%dT%H:%M'], localize=False)
    end_date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=False,
                                   input_formats=['%Y-%m-%dT%H:%M'], localize=False)
    count_iteration = forms.IntegerField(required=False, min_value=1)

    task_type = forms.ChoiceField(choices=[(0, "Existing task"), (1, "New task")], required=False,
                                  widget=forms.RadioSelect(), initial=0)

    board_title = forms.CharField(required=False)

    board_id = forms.IntegerField(initial=None, required=False)

    task_title = forms.CharField(required=False)

    task_id = forms.IntegerField(initial=None, required=False)

    def clean_periodicity(self):
        periodicity = self.cleaned_data[model.PLAN_PERIODICITY]
        periodicity = periodicity.strip() + ' '
        pattern = re.compile(periodicity_regex)
        match = pattern.match(periodicity)
        if match:
            result = match.groupdict()
            return result
        else:
            raise ValidationError('Period format needs to be "##Y ##M ##D ##h ##m"')

    def clean_end_type(self):
        end_type = self.cleaned_data.get(model.PLAN_END_TYPE)
        return int(end_type)

    # def clean_interval(self):
    #     interval = self.cleaned_data.get(model.PLAN_INTERVAL)
    #     return int(interval)

    def clean_count_iteration(self):
        count_iteration = self.cleaned_data.get(model.PLAN_COUNT_ITERATION)
        if count_iteration:
            return int(count_iteration)
        return count_iteration

    def clean_task_id(self):
        form_data = self.cleaned_data
        task_id = form_data.get(model.TASK_ID, None)
        title = form_data.get(model.TASK_TITLE, None)
        if not task_id and not title:
            raise ValidationError("You must specify existing task or add new.")
        return task_id

    def clean_task_title(self):
        form_data = self.cleaned_data
        task_id = form_data.get(model.TASK_ID, None)
        title = form_data.get(model.TASK_TITLE, None)
        if not task_id and not title:
            raise ValidationError("You must specify existing task or add new.")
        return

    def clean_start_date(self):
        form_data = self.cleaned_data
        start_date = form_data.get(model.PLAN_START, None)
        end_date = form_data.get(model.PLAN_END, None)
        if start_date is not None and end_date is not None:
            if end_date < start_date:
                raise ValidationError("Start date can't be later than end date")
        return start_date

    def clean_end_date(self):
        form_data = self.cleaned_data
        start_date = form_data.get(model.PLAN_START, None)
        end_date = form_data.get(model.PLAN_END, None)
        if start_date is not None and end_date is not None:
            if end_date < start_date:
                raise ValidationError("Start date can't be later than end date")
        return end_date

IRONTASK/irontaskweb/irontaskweb/templates/task/edit.html
{% extends "base.html" %}

{% block head_title %}
    <title>Task's {% if is_creation %}creation{% else %}update{% endif %}</title>
{% endblock %}

{% block content %}
{% load filters %}
<div style="height:100vh;">
    <form id="task_form" action="{% if is_creation %}{% url 'irontask:add_task' %}{% else %}{% url 'irontask:update_task' task_id %}{% endif %}" method="post">
        {% csrf_token %}
        <div class="form-group row" style="align-items:center;">
            <div class="col-sm-2">
                <h1>
                    <span class="badge badge-secondary">
                        {% if task_id %}
                            {{task_id}}
                        {% else %}
                            <span class="glyphicon glyphicon-hourglass"></span>
                        {% endif %}
                        Task
                    </span>
                </h1>
            </div>
            <div class="col-sm-10">
                {{form.title|css:'form-control form-control-lg'}}
                <div>
                    {% for error in form.title.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Tags</label>
            <div class="col-sm-10">
                {{form.tags}}
                <div>
                    {% for error in form.tags.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-10">
                {{form.description|css:'form-control'}}
                <div>
                    {% for error in form.description.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Status</label>
            <div class="col-sm-10">
                {{form.status|css:'form-control'}}
                <div>
                    {% for error in form.status.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Priority</label>
            <div class="col-sm-10">
                {{form.priority|css:'form-control'}}
                <div>
                    {% for error in form.priority.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Board</label>
            <div class="col-sm-10">
                {{form.board_title|css:'form-control'}}
                {{form.board_id.as_hidden}}
                <div>
                    {% for error in form.board_id.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
                <div>
                    {% for error in form.board_title.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Date type:</label>
            {% for checkbox in form.date_type %}
            <div class="form-check form-check-inline" onclick="changeDateType()">
                {{checkbox}}
            </div>
            {% endfor %}
        </div>

        <div class="form-group row" id="start-end-row">
            <label class="col-sm-2 col-form-label">Start</label>
            <div class="col-sm-4">
                {{form.start_date|css:'form-control'}}
                <div>
                    {% for error in form.start_date.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            <label class="col-sm-2 col-form-label">End</label>
            <div class="col-sm-4">
                {{form.end_date|css:'form-control'}}
                <div>
                    {% for error in form.end_date.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>

        </div>

        <div class="form-group row event" id="event-row">
            <label class="col-sm-2 col-form-label">Event</label>
            <div class="col-sm-5">
                {{form.event_date|css:'form-control'}}
                <div>
                    {% for error in form.event_date.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>

        <button type="button" onclick="submitForm()" class="btn btn-success d-flex mx-auto">{% if is_creation %}Add{% else %}Update{% endif %}</button>
    </form>
</div>
<script>
    $(document).ready(function() {
        changeDateType();

        $('#id_board_title').autocomplete({
            minLength: 1,
            delay: 300,
            source: function(request, response) {
                $.post({
                    url: '{% url 'irontask:get_boards' %}',
                    data: { 'term': request.term, 'csrfmiddlewaretoken': "{{ csrf_token }}" },
                    success: function(data) {
                        response(data);
                    }
                });
            },
            focus: function(event, ui) {
                $('#id_board_title').val( ui.item.label );
                return false;
            },
            select: function(event, ui) {
                $('#id_board_title').val(ui.item.label)
                $('#id_board_id').val(ui.item.value);
                return false;
            }
        });
    });

    function submitForm() {
        $('#task_form').submit();
    }

    function changeDateType() {
        if($('#id_date_type_0:checked').length) {
            $('#id_start_date').val('');
            $('#id_end_date').val('');
            $('#id_event_date').val('');
            $('#start-end-row').css('display', 'none')
            $('#event-row').css('display', 'none')
        }
        if($('#id_date_type_1:checked').length) {
            $('#id_event_date').val('');
            $('#start-end-row').css('display', 'flex')
            $('#event-row').css('display', 'none')
        }
        if($('#id_date_type_2:checked').length) {
            $('#id_start_date').val('');
            $('#id_end_date').val('');
            $('#start-end-row').css('display', 'none')
            $('#event-row').css('display', 'flex')
        }
    }
</script>
{% endblock %}

IRONTASK/irontaskweb/irontaskweb/templates/task/tasks.html
{% extends "base.html" %}

{% block head_title %}
	<title>Tasks</title>
{% endblock %}

{% block content %}
<div class="h-100">
    <h3>Tasks</h3>

    <div class="card-deck">
        {% for task in tasks %}
            {% include "components/task_component.html" with task=task %}
        {% empty %}
        <div>You have not any tasks</div>
        {% endfor %}
    </div>
</div>
{% endblock %}